POST http://localhost:4002/users
content-type: application/json

{
    "name": "David",
    "password": "123"
}

###

GET http://localhost:4002/users

###

GET http://localhost:4002/users/20e6d9bc-1a44-4e58-be73-985720771f7d

###

PUT http://localhost:4002/users/20e6d9bc-1a44-4e58-be73-985720771f7d
content-type: application/json

{
    "name": "Antonio Alves",
    "password": "123"
}

### 
DELETE http://localhost:4002/users/806b8aee-8171-4917-9c78-41493b079c9a